export { default as Post} from "./Post/Post"
export { default as Category} from "./Category/Category"
export { default as Authors} from "./Authors/Authors"
export { default as Addcategory} from "./Addcategory/Addcategory"
export { default as Updatecategory} from "./Updatecategory/Updatecategory"
export { default as Admin} from "./Admin"